---
# You can create this secret in Vault by running the following commands:
# oc rsh -n vault vault-0 vault kv put -mount=kv idp/labldap-ldap-bind-password bindPassword="$(cat ~/.ldap-bind-pw)"
kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: labldap-ldap-bind-password
  namespace: openshift-config
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hoh-vault
  data:
    - secretKey: bindPassword # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: idp/labldap-ldap-bind-password # name of the secret under the target Vault path
        property: bindPassword # # name of the key in that named Vault secret
  target:
    creationPolicy: None
    deletionPolicy: Retain
    name: labldap-ldap-bind-password # The name of the k8s Secret to be created
