---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec: {}
#  nodeSelector:
#    nodeSelectorTerms:
#      - matchExpressions:
#          - key: node-role.kubernetes.io/infra
#            operator: Exists
#  tolerations:
#    - effect: NoSchedule
#      key: node.ocs.openshift.io/storage
#      operator: Equal
#      value: 'true'
#    - effect: NoSchedule
#      key: node-role.kubernetes.io/infra
#      operator: Equal
#      value: "reserved"
#    - effect: NoExecute
#      key: node-role.kubernetes.io/infra
#      operator: Equal
#      value: "reserved"
#