apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    cluster.ocs.openshift.io/local-devices: 'true'
    storagesystem.odf.openshift.io/watched-by: ocs-storagecluster-storagesystem
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
  finalizers:
    - storagecluster.ocs.openshift.io
spec:
  #version: 4.9.0
  storageDeviceSets:
    - name: ocs-deviceset-odf
      count: 3
      config: {}
      preparePlacement: {}
      replica: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: odf
          volumeMode: Block
        status: {}
      placement: {}
      resources:
        limits:
          cpu: '2'
          memory: 5Gi
        requests:
          cpu: '1'
          memory: 5Gi

  # https://access.redhat.com/articles/6408481
  placement:
    all:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      #- effect: NoSchedule
      #  key: node.ocs.openshift.io/storage
      #  operator: Equal
      #  value: "true"
    mds:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      #- effect: NoSchedule
      #  key: node.ocs.openshift.io/storage
      #  operator: Equal
      #  value: "true"
    noobaa-core:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      #- effect: NoSchedule
      #  key: node.ocs.openshift.io/storage
      #  operator: Equal
      #  value: "true"
    rgw:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      #- effect: NoSchedule
      #  key: node.ocs.openshift.io/storage
      #  operator: Equal
      #  value: "true"