apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ztp-as-a-service-consolelinks-aap2
  namespace: rhacm-policies
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cs-aap2-controller
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleLink
                metadata:
                  name: ansible-controller-console-link
                spec:
                  applicationMenu:
                    imageURL: https://upload.wikimedia.org/wikipedia/commons/2/24/Ansible_logo.svg
                    section: Ansible Automation Platform 2
                  href: 'https://{{ ( index ( lookup "route.openshift.io/v1"  "Route" "aap2" "ac-tower").status.ingress 0 ).host }}'
                  location: ApplicationMenu
                  text: Ansible Controller/Tower
          pruneObjectBehavior: DeleteIfCreated
