# vault-values.yaml

global:
  openshift: true

injector:
  image:
    repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
    tag: "1.1.0-ubi"

  agentImage:
    repository: "registry.connect.redhat.com/hashicorp/vault"
    tag: "1.12.1-ubi"

server:
  image:
    repository: "registry.connect.redhat.com/hashicorp/vault"
    tag: "1.12.1-ubi"
  ha:
    enabled: false
  dev:
    enabled: false
  route:
    enabled: true
    host: ''
    tls:
      termination: edge

ui:
  enabled: true
