apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    storagesystem.odf.openshift.io/watched-by: ocs-storagecluster-storagesystem
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
  finalizers:
    - storagecluster.ocs.openshift.io
spec:
  storageDeviceSets:
    - config: {}
      resources:
        limits:
          cpu: '2'
          memory: 5Gi
        requests:
          cpu: '1'
          memory: 5Gi
      placement: {}
      name: ocs-deviceset-gp2
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 512Gi
          storageClassName: gp2
          volumeMode: Block
        status: {}
      count: 1
      replica: 3
      portable: true
      preparePlacement: {}
  encryption:
    kms: {}
  mirroring: {}
  resources:
    mds:
      limits:
        cpu: '3'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 8Gi
    rgw:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 4Gi
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  arbiter: {}
  nodeTopologies: {}
  externalStorage: {}
  #version: {{ ocp_version_slice[0] }}.{{ ocp_version_slice[1] }}.0

  # https://access.redhat.com/articles/6408481
  placement:
    all:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    mds:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    noobaa-core:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    rgw:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"