---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: rhacm-subscription-cluster-admin
subjects:
  - kind: ServiceAccount
    name: application-manager
    namespace: open-cluster-management-agent-addon
  - kind: ServiceAccount
    name: governance-policy-framework-sa
    namespace: open-cluster-management-agent-addon
  - kind: ServiceAccount
    name: iam-policy-controller-sa
    namespace: open-cluster-management-agent-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin