{{- if .Values.mirror_registry.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.mirror_registry.configmapName }}
  namespace: multicluster-engine
data:
  ca-bundle.crt: |
{{ .Files.Get "files/ca-bundle.crt" | indent 4 }}
  registries.conf: |
{{ .Files.Get "files/registries.conf" | indent 4 }}
{{- end }}