{{- if .Values.rhacm.mce.enabled }}
---
## Unless you need to override things this doesn't need to be applied
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  labels:
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
  name: multiclusterengine
spec:
  availabilityConfig: Basic
  overrides:
    components:
      - name: assisted-service
        enabled: true
      - name: cluster-lifecycle
        enabled: true
      - name: cluster-manager
        enabled: true
      - name: discovery # the discovery add-on allows you to connect to OCM and discover clusters for import - nice, but not useful for accounts that have a lot of clusters
        enabled: false
      - name: hive # ipi provisioning stuff
        enabled: true
      - name: server-foundation
        enabled: true
      - name: managedserviceaccount-preview
        enabled: true
      - name: hypershift-preview
        enabled: true
      - name: console-mce
        enabled: true
      - name: cluster-proxy-addon
        enabled: false
  targetNamespace: multicluster-engine
# https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/install/installing#installing-on-infra-node
{{- if .Values.rhacm.mce.infraNodes }}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      operator: Exists
  nodeSelector:
    node-role.kubernetes.io/infra: ""
{{- end }}
{{- end }}
