apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: ztp-as-a-service-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: ztp-as-a-service-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: ztp-as-a-service-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - ztp-as-a-service
policies:
  - name: ztp-as-a-service
    manifests:
      - path: manifests