apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: deploy-aap2-controller-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: deploy-aap2-controller-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: ztp-as-a-service-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - deploy-aap2-controller
policies:
  - name: deploy-aap2-controller
    manifests:
      - path: manifests
        patches:
          - apiVersion: automationcontroller.ansible.com/v1beta1
            kind: AutomationController
            metadata:
              name: ac-tower
              namespace: aap2
            spec:
              #bundle_cacert_secret: cluster-root-ca-aap2-bundle
              admin_email: kmoini@redhat.com
              admin_user: admin