---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mcm-cluster-importer-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: mcm-cluster-importer
