---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: mcm-importer-cluster-admin
subjects:
  - kind: ServiceAccount
    name: mcm-cluster-importer
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin