apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ansible-automation-platform-operator.ansible-automation-platfor: ''
  name: ansible-automation-platform-operator
  namespace: aap2
spec:
  # we'll patch this in via the policygenerator
  #channel: stable-2.3-cluster-scoped
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# Uncomment the following lines to run the Operator on a set of tainted nodes.
#  config:
#    tolerations:
#    - effect: NoSchedule
#      key: node-role.kubernetes.io/infra
#      operator: Equal
#      value: "reserved"
#    - effect: NoExecute
#      key: node-role.kubernetes.io/infra
#      operator: Equal
#      value: "reserved"
