apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: global-config-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: global-config-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: all-openshift-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - global-config
policies:
  - name: global-config
    manifests:
      - path: manifests