apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
spec:
  template:
    spec:
      containers:
      - name: vault-init
        image: registry.redhat.io/openshift4/ose-cli:v4.6
        imagePullPolicy: IfNotPresent
        #env:
        #- name: "http_proxy"
        #  value: "http://userid:password@proxy.xyzco.com:8080"
        #- name: "https_proxy"
        #  value: "http://uesrid:password@proxy.xyzco.com:8080"
        #- name: "no_proxy"
        #  value: ".xyzco.com,172.30.0.0/16,.svc,.svc.cluster.local,.local,10.0.0.0/8,100.64.0.0/10"
        command:
        - /bin/sh
        - -c
        - >-
          VAULT_STATUS=$(oc exec -it vault-0 -- vault operator -status)
          if [ "$VAULT_STATUS" -eq "2" ]; then
            echo "Vault is already initialized"
            exit 0
          fi
          
          VAULT_INIT=$(oc exec -it vault-0 -- vault operator init -key-shares=1 -key-threshold=1)
          echo "$VAULT_INIT" > .vault-init
          cat .vault-init
          UNSEAL_KEY=$(cat .vault-init | grep "Unseal Key" | sed 's/Unseal Key 1: //')
          ROOT_TOKEN=$(cat .vault-init | grep "Initial Root Token" | sed 's/Initial Root Token: //')
          oc create secret generic vault-token-auth --from-literal=token="${ROOT_TOKEN}" -n vault
          oc exec -it vault-0 -- vault operator unseal "$UNSEAL_KEY"
          oc exec -it vault-0 -- vault login "${ROOT_TOKEN}"
          oc exec -it vault-0 -- vault secrets enable -version=2 kv
          oc exec -it vault-0 -- vault secrets enable pki
          oc exec -it vault-0 -- vault secrets tune -max-lease-ttl=87600h pki
          oc exec -it vault-0 -- vault auth enable kubernetes
          oc exec -it vault-0 -- vault write auth/kubernetes/config kubernetes_host="https://\$KUBERNETES_PORT_443_TCP_ADDR:443" token_reviewer_jwt=@/var/run/secrets/kubernetes.io/serviceaccount/token kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt issuer="https://kubernetes.default.svc.cluster.local"
          oc exec -it vault-0 -- vault write auth/kubernetes/role/issuer bound_service_account_names="*" bound_service_account_namespaces="*" ttl=20m
      restartPolicy: OnFailure
      serviceAccountName: vault-init-sa