apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: additional-trust-bundle-policygenerator
  namespace: rhacm-applications
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - additional-trust-bundle-policygenerator
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-kenmoini-multiverse-of-multicluster-madness
  namespace: rhacm-channels
spec:
  type: Git
  pathname: 'https://github.com/kenmoini/multiverse-of-multicluster-madness'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: manifests/additional-trust-bundle
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: additional-trust-bundle-policygenerator
  name: additional-trust-bundle-policygenerator
  namespace: rhacm-applications
spec:
  channel: rhacm-channels/additional-trust-bundle-policygenerator
  placement:
    placementRef:
      kind: PlacementRule
      name: management-clusters
