apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-install-mco
  namespace: rhacm-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: o11y-geo-hub-clusters
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: install-mco-prereqs
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: install-mco
