apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-install-loki-stack
  namespace: rhacm-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: o11y-geo-hub-clusters
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: install-loki-stack-prereqs
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: install-loki-stack
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: copy-loki-secret
