apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-install-hoh-grafana
  namespace: rhacm-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: hub-of-hubs-clusters
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: install-hoh-grafana
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: install-hoh-grafana-dashboards
