---
# You can create this secret in Vault by running the following commands:
# oc rsh -n vault vault-0 vault kv put -mount=kv idp/google-rh-sso clientSecret="$(cat ~/.google-sso-cs)"

kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: redhatsso-google-oauth-client-secret
  namespace: openshift-config
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hoh-vault
  data:
    - secretKey: clientSecret # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: idp/google-rh-sso # name of the secret under the target Vault path
        property: clientSecret # # name of the key in that named Vault secret
  target:
    creationPolicy: None
    deletionPolicy: Retain
    name: redhatsso-google-oauth-client-secret # The name of the k8s Secret to be created
