---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aap2-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: aap2
  - kind: ServiceAccount
    name: ac-tower
    namespace: aap2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: aap2
subjects:
  - kind: ServiceAccount
    name: default
    namespace: aap2
  - kind: ServiceAccount
    name: ac-tower
    namespace: aap2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'