apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: lso-odf-aws-deployed-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: lso-odf-aws-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: aws-openshift-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - lso-odf-aws
policies:
  - name: lso-odf-aws
    manifests:
      - path: aws