apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: lso-odf-local-infra-deployed-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: lso-odf-local-infra-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: geo-hub-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - lso-odf-local-infra
policies:
  - name: lso-odf-local-infra
    manifests:
      - path: local-infra-nodes