---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-kenmoini-multiverse-of-multicluster-madness
  namespace: rhacm-channels
spec:
  type: Git
  pathname: 'https://github.com/kenmoini/multiverse-of-multicluster-madness'
