# Default values for ztp-as-a-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mirror_registry:
  enabled: false
  configmapName: mirror-registry-config-map
  ca-bundle.crt: |
    
  config: |
    unqualified-search-registries = ["registry.access.redhat.com", "quay.io", "docker.io"]
    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-release"
      mirror-by-digest-only = true
      
      [[registry.mirror]]
        location = "quay.io/openshift-release-dev/ocp-release"
    [[registry]]
      prefix = ""
      location = "quay.io/ocpmetal/assisted-installer"
      mirror-by-digest-only = false
      
      [[registry.mirror]]
        location = "quay.io/ocpmetal/assisted-installer"
    [[registry]]
      prefix = ""
      location = "quay.io/ocpmetal/assisted-installer-agent"
      mirror-by-digest-only = false
      
      [[registry.mirror]]
        location = "quay.io/ocpmetal/assisted-installer-agent"
    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
      mirror-by-digest-only = true
      
      [[registry.mirror]]
        location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"

rhacm:
  mce:
    enabled: true
    infraNodes: true

aap2:
  configure_controller: true
  clusterLocal: true
  namespace: aap2

proxy:
  enabled: false
  httpProxy: http://proxy.example.com:8080
  httpsProxy: http://proxy.example.com:8080
  noProxy: "localhost"

http_mirror:
  enabled: true
  namespace: ztp-mirror
  mirrored_versions:
    - "4.9"
    - "4.10"
    - "4.11"
  pvc_size: 20Gi

gitea:
  enabled: true
  clusterLocal: true
  namespace: gitea
  config:
    adminUser: opentlc-mgr
    adminPassword: "r3dh4t123!"
    adminEmail: opentlc-mgr@redhat.com
    storageClassName: default-sc
    createUsers:
      enabled: true
      format: "user-%d"
      count: 10
      password: openshift
    migrations:
      enabled: true
      repos:
        - repo: https://github.com/Red-Hat-SE-RTO/openshift-ztp.git
          name: openshift-ztp
          private: false



aap2Controller:
  enabled: true
  clusterLocal: true

### lol most the rest of this stuff is not needed, just the defaults from the `helm create` command

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
