---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm-policies
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: rhacm-policies
  name: rhacm-policies
  namespace: rhacm-policies
spec:
  channel: rhacm-channels/ggithubcom-kenmoini-multiverse-of-multicluster-madness
  placement:
    placementRef:
      kind: PlacementRule
      name: local-cluster
