apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: idp-google-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: idp-google-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: idp-google-auth-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - idp-google
policies:
  - name: idp-google
    manifests:
      - path: google